import type { PropertyListing, Neighborhood, Agent } from "@/types";

export const SAMPLE_NEIGHBORHOODS: Neighborhood[] = [
  { id: "n1", name: "Palm Beach",    slug: "palm-beach",    tagline: "Aruba's most vibrant beachfront strip", description: null, cover_image_url: null, latitude: 12.5662, longitude: -70.0432, is_featured: true,  sort_order: 1, seo_title: null, seo_description: null },
  { id: "n2", name: "Malmok",        slug: "malmok",        tagline: "Quiet, upscale beachside living",       description: null, cover_image_url: null, latitude: 12.5881, longitude: -70.0604, is_featured: true,  sort_order: 2, seo_title: null, seo_description: null },
  { id: "n3", name: "Eagle Beach",   slug: "eagle-beach",   tagline: "One of the world's finest beaches",     description: null, cover_image_url: null, latitude: 12.5528, longitude: -70.0481, is_featured: true,  sort_order: 3, seo_title: null, seo_description: null },
  { id: "n4", name: "Noord",         slug: "noord",         tagline: "The residential heart of the island",   description: null, cover_image_url: null, latitude: 12.5700, longitude: -70.0300, is_featured: false, sort_order: 4, seo_title: null, seo_description: null },
  { id: "n5", name: "Oranjestad",    slug: "oranjestad",    tagline: "Capital city living and commerce",      description: null, cover_image_url: null, latitude: 12.5092, longitude: -70.0086, is_featured: false, sort_order: 5, seo_title: null, seo_description: null },
  { id: "n6", name: "Tierra del Sol",slug: "tierra-del-sol",tagline: "Gated golf community with panoramas",  description: null, cover_image_url: null, latitude: 12.6078, longitude: -70.0638, is_featured: true,  sort_order: 6, seo_title: null, seo_description: null },
];

export const SAMPLE_AGENT: Agent = {
  id: "a1",
  full_name: "Muna Habash",
  slug: "muna-habash",
  title: "Licensed Real Estate Broker",
  bio: null,
  photo_url: null,
  phone_aruba: "+297 593 4647",
  whatsapp: "2975934647",
  email: "muna@mpgaruba.com",
  languages: ["English", "Arabic", "Dutch", "Papiamento"],
  specialties: ["Luxury Villas", "Investment", "Foreign Buyers"],
};

export const SAMPLE_PROPERTIES: PropertyListing[] = [
  {
    id: "p1",
    title: "[Sample] Grand Villa at Malmok",
    slug: "sample-grand-villa-malmok",
    contract_type: "sale",
    property_type: "villa",
    status: "featured",
    price_usd: 3880000,
    price_awg: 6948200,
    price_on_request: false,
    bedrooms: 5,
    bathrooms: 5,
    lot_size_m2: 1218,
    lot_size_ft2: 13110,
    build_area_m2: 567,
    build_area_ft2: 6103,
    land_type: "long_lease",
    pool: true,
    ocean_view: true,
    beachfront: false,
    furnished: false,
    primary_image_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    location_text: "Malmok, Aruba",
    is_featured: true,
    is_luxury: true,
    is_new: false,
    is_investment: false,
    published_at: new Date().toISOString(),
    neighborhood_name: "Malmok",
    neighborhood_slug: "malmok",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
  {
    id: "p2",
    title: "[Sample] Beachfront Condo at Palm Beach",
    slug: "sample-beachfront-condo-palm-beach",
    contract_type: "sale",
    property_type: "condominium",
    status: "active",
    price_usd: 650000,
    price_awg: 1163500,
    price_on_request: false,
    bedrooms: 2,
    bathrooms: 2,
    lot_size_m2: null,
    lot_size_ft2: null,
    build_area_m2: 120,
    build_area_ft2: 1291,
    land_type: "long_lease",
    pool: false,
    ocean_view: true,
    beachfront: true,
    furnished: true,
    primary_image_url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    location_text: "Palm Beach, Aruba",
    is_featured: true,
    is_luxury: false,
    is_new: true,
    is_investment: true,
    published_at: new Date().toISOString(),
    neighborhood_name: "Palm Beach",
    neighborhood_slug: "palm-beach",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
  {
    id: "p3",
    title: "[Sample] Family Home in Noord",
    slug: "sample-family-home-noord",
    contract_type: "sale",
    property_type: "residential",
    status: "active",
    price_usd: 395000,
    price_awg: 707050,
    price_on_request: false,
    bedrooms: 3,
    bathrooms: 2,
    lot_size_m2: 650,
    lot_size_ft2: 6997,
    build_area_m2: 210,
    build_area_ft2: 2260,
    land_type: "freehold",
    pool: true,
    ocean_view: false,
    beachfront: false,
    furnished: false,
    primary_image_url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    location_text: "Noord, Aruba",
    is_featured: false,
    is_luxury: false,
    is_new: false,
    is_investment: false,
    published_at: new Date().toISOString(),
    neighborhood_name: "Noord",
    neighborhood_slug: "noord",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
  {
    id: "p4",
    title: "[Sample] Modern Apartment for Rent — Oranjestad",
    slug: "sample-apartment-rent-oranjestad",
    contract_type: "rent",
    property_type: "residential",
    status: "active",
    price_usd: 1800,
    price_awg: 3222,
    price_on_request: false,
    bedrooms: 2,
    bathrooms: 1,
    lot_size_m2: null,
    lot_size_ft2: null,
    build_area_m2: 95,
    build_area_ft2: 1022,
    land_type: "long_lease",
    pool: false,
    ocean_view: false,
    beachfront: false,
    furnished: true,
    primary_image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    location_text: "Oranjestad, Aruba",
    is_featured: false,
    is_luxury: false,
    is_new: true,
    is_investment: false,
    published_at: new Date().toISOString(),
    neighborhood_name: "Oranjestad",
    neighborhood_slug: "oranjestad",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
  {
    id: "p5",
    title: "[Sample] Luxury Villa, Tierra del Sol Golf Estate",
    slug: "sample-luxury-villa-tierra-del-sol",
    contract_type: "sale",
    property_type: "villa",
    status: "new",
    price_usd: 1250000,
    price_awg: 2237500,
    price_on_request: false,
    bedrooms: 4,
    bathrooms: 3.5,
    lot_size_m2: 850,
    lot_size_ft2: 9149,
    build_area_m2: 380,
    build_area_ft2: 4090,
    land_type: "long_lease",
    pool: true,
    ocean_view: false,
    beachfront: false,
    furnished: false,
    primary_image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    location_text: "Tierra del Sol, Aruba",
    is_featured: true,
    is_luxury: true,
    is_new: true,
    is_investment: true,
    published_at: new Date().toISOString(),
    neighborhood_name: "Tierra del Sol",
    neighborhood_slug: "tierra-del-sol",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
  {
    id: "p6",
    title: "[Sample] Freehold Land Plot — Savaneta",
    slug: "sample-land-savaneta",
    contract_type: "sale",
    property_type: "land",
    status: "active",
    price_usd: 120000,
    price_awg: 214800,
    price_on_request: false,
    bedrooms: null,
    bathrooms: null,
    lot_size_m2: 900,
    lot_size_ft2: 9688,
    build_area_m2: null,
    build_area_ft2: null,
    land_type: "freehold",
    pool: false,
    ocean_view: false,
    beachfront: false,
    furnished: false,
    primary_image_url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    location_text: "Savaneta, Aruba",
    is_featured: false,
    is_luxury: false,
    is_new: false,
    is_investment: true,
    published_at: new Date().toISOString(),
    neighborhood_name: "Savaneta",
    neighborhood_slug: "savaneta",
    agent_name: "Muna Habash",
    agent_photo: null,
    agent_whatsapp: "2975934647",
    agent_phone: "+297 593 4647",
  },
];
